version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - checkout
#      - run:
#          name: update-npm
#          command: 'sudo npm install -g npm@latest'
#      - restore_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
#      - save_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#          paths:
#          - ./node_modules
      - run:
         name: run-debug
         command: npm run build:dev
      - run:
         name: run-prod
         command: npm run build:prod
      - run:
         name: run-prod-aot
         command: npm run build:prod:aot
      - run:
         name: run-test
         command: npm test

#    # TODO add protractor tests with npm run webdriver:update && npm run e2e